import type { Experience_Item_Details } from "../../components/InfoList";

export const experienceData: Experience_Item_Details[] = [
	{
		id: 'e1',
		type: 'Experience',
		companyName: "Qudasoft",
		imageURL: "https://media.licdn.com/dms/image/v2/C4D0BAQFUvq-qbL6RsQ/company-logo_100_100/company-logo_100_100/0/1650564252303?e=1788998400&v=beta&t=ItW94OCFqfgw3NWJcZcHp5pZYQzW6tL-XZVw8hlvim4",
		imageAlt: 'Qudasoft image',
		designation: "Software Developer",
		employmentType: "Full-time",
		location: "Pune District, Maharashtra, India",
		mode: "Remote",
		skills: ["React.js", "Next.js", "Material UI", "Redux", "AWS Amplify", "JavaScript", "Salesforce", "LWC", "Apex", "Node", "S3"],
		startDate: "Jul 2024",
		endDate: "Present",
		points: [
			"Built enterprise customer portals with React.js, Material UI, Redux Toolkit, and AWS.",
			"Delivered customer-facing features and complex business workflows, integrating REST APIs and Salesforce across multiple applications.",
			"Worked with backend, Salesforce, QA, and design teams to deliver maintainable, production-ready features.",
		],
	},
	{
		id: 'e2',
		type: 'Experience',
		companyName: "Incipient Infotech",
		imageURL: "https://media.licdn.com/dms/image/v2/C4D0BAQHtkPNSOPwiMA/company-logo_100_100/company-logo_100_100/0/1671175097160/incipientinfo_logo?e=1788998400&v=beta&t=MgzV73IAJTgs4nxAu0oLMSwZxsgKynUmTSEQNyaQOu8",
		imageAlt: 'Incipient Infotech image',
		designation: "React js developer",
		employmentType: "Full-time",
		location: "Ahmedabad, Gujarat, India",
		mode: "Hybrid",
		skills: ["React.js", "Redux.js", "Next.js", "Material-UI", 'Web3',],
		startDate: "Jan 2023",
		endDate: "Apr 2024",
		points: [
			"Built React.js and Next.js applications with reusable components, Redux, and REST APIs.",
			"Delivered features for Web3, NFT, and marketing platforms, including wallet integrations, blockchain workflows, and Unity WebGL.",
		],
	},
	{
		id: 'e3',
		type: 'Experience',
		companyName: "SoluLab",
		imageURL: "https://media.licdn.com/dms/image/v2/D4D0BAQGcQfe9spIjQA/company-logo_100_100/B4DZwsXbZtKkAQ-/0/1770270865448/solulab_logo?e=1788998400&v=beta&t=siGMvVaEEiPDytQnknvzffI3TE3gMtYuF380Qbr9Xx0",
		imageAlt: "SoluLab",
		designation: "React js developer",
		employmentType: "Full-time",
		location: "Ahmedabad, Gujarat, India",
		mode: "Remote",
		skills: ["React.js", "Redux.js", "Next.js"],
		startDate: "Nov 2021",
		endDate: "Nov 2022",
		points: [
			"Developed and enhanced blockchain-based web applications using React.js and Next.js by implementing frontend features and integrating backend APIs.",
			"Worked on existing production projects, resolving bugs and delivering new functionality in collaboration with senior developers.",
		],
	},
	{
		id: 'e4',
		type: 'Experience',
		companyName: "Pepcoding",
		imageURL: "https://media.licdn.com/dms/image/v2/D560BAQHY4q5-ajMQzw/company-logo_100_100/company-logo_100_100/0/1702907971309/pepcoding_logo?e=1788998400&v=beta&t=mrWu65BnhAPyg_5y4pQKudTkWD4xTWKw7ByDBbwK7BY",
		imageAlt: '',
		designation: "React developer intern",
		employmentType: "Intership",
		location: "Noida, Uttar Pradesh, India",
		mode: "Remote",
		skills: ["React.js", "Redux.js", "Next.js"],
		startDate: "Feb 2021",
		endDate: "Nov 2021",
		points: [
			"Gained hands-on experience with JavaScript, Redux, Firebase, REST APIs and Git through real-world projects and mentorship.",
		],

	},
];
