import "@/styles/globals.css";
import LogoutButton from "./logout";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body>
				<LogoutButton />
				{children}
			</body>
		</html>
	);
}
